# Generated by Django 4.1.3 on 2022-11-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
